### PR TITLE
Added support for Foundry VTT version 9

### PR DESCRIPTION
**Pull request by ClausWiingreen**
I added a fallback incase the attribute "data-entity-id" was not found to look at attribute "data-document-id".

I still need to test this with older versions of Foundry and on other computers than my own.

Should resolve issue #5

### CODE REVIEW

**Review by chrisjbrown — APPROVED** [review]

**Comment by chrisjbrown** [comment]
tested and works 👍

**Comment by Zamrod** [comment]
Even with this version I'm sill getting an error:
```
Entities.js:8 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'data')
[Detected 1 package: split-journal]
    at new FurnaceSplitJournal (Entities.js:8)
    at Object.callback (Entities.js:166)
    at HTMLLIElement.<anonymous> (foundry.js:43601)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)
```

**Review by Zamrod — CHANGES_REQUESTED** [review]
Line 164 should be:
(typeof entityId == "undefined") entityId = header.attr("data-document-id"); 
It should check if it is undefined, not if it is NOT undefined.

**Comment by ClausWiingreen** [comment]
@Zamrod you're completely right will fix it. Thank you for verifying.

**Comment by anthonyronda** [comment]
Sorry for the delay! We didn't have eyes on this one because we don't have a maintainer.

I understand that this one is being transferred to another maintainer soon, but if this happens with another of our modules labeled "Adopt Me!", the best way to get eyes on a PR is to mention it in our discord server's #league-modules channel

**Pull request merged**
